### ISSUE TITLE
[solved] what is the requirement for Berkerley DB ? => real db 1.x is required

### ISSUE THREAD

**Issue by yopito** [lichray/nvi2#100]
hello,
I've built successfully nvi2 with db 5.3 or db 18.1, both with db 1.85 compat mode enabled ("`--enable-compat185`")
However, nvi2 runtime fails with this message from (lib)db:
`Berkeley DB: DB 1.85's recno bfname field is not supported.`

So nvi2 requires a "real" db 1.85 ? 1.85 compat mode is not supported ? or my build is a mess ?

**Comment by lichray** [comment]
I think yes then, nvi's mechanism for keeping a recovery file is to have a B-tree in memory as well as on disk.

**Comment by yopito** [comment]
I've also built nvi 1.81.6 with either db 5 or db 18: no such a problem, its runtime is fine.

**Comment by lichray** [comment]
nvi 1.8x and this project are of different code bases. The former is built on top of db>=3 and subjects to Sleepycat/GPL, this project is BSD-licensed, only.

**Comment by yopito** [comment]
yep, I see that nvi2 comes from nvi 1.79, it was just a "comparison".
So have to use "real" db 1.x for nvi2. 
Thanks for your reply.
