### ISSUE TITLE
Truncation

### ISSUE THREAD

**Issue by bentley** [lichray/nvi2#12]
The truncation behavior for characters invalid in the current encoding is... unfriendly. This is a regression from 1.79, where non-ASCII bytes are visually escaped and don't cause weird behavior.

- Files with a bad character should not be truncated. Currently on write, the file is truncated at the first line with a bad character. This is really unpleasant, especially since there's _no_ way to undo it!

- Lines with a bad character should not interfere with searching, scrolling, etc. They should be displayed (with proper escapes) and not shown blank on the screen.

**Comment by lichray** [comment]
One thought from @delphij: ask the user to reload the file in 8-bit mode when such an error occurs.
