### ISSUE TITLE
Sometimes `db` actually `d0`'s

### ISSUE THREAD

**Issue by concussious** [lichray/nvi2#136]
When copying text from terminal to terminal with the mouse, lots of spaces are generated instead of tabs. When manually cleaning a copied line [0] like:
```
      Something      *Something else
```
With the cursor at the `*`, by using `db`, all characters in the line before the cursor are deleted instead of the expected behavior of deleting to the end of the previous word.

`dw` works as expected, deleting to the beginning of the next word when the cursor is after the first `g`. Observed in FreeBSD 15-CURRENT.

[0] Which is maybe not the smart way to do it, tips greatly appreciated.

Thanks!

**Comment by lichray** [comment]
I observed
```
      *Something else
```
after pressing `db` on `*` at the `main` branch. What did you observe?

**Comment by concussious** [comment]
I observed
```
*Something else
```
However I just tried again and I'm getting the correct behavior, even after copying (what I think was) the same line structure. I'm sorry.

**Comment by concussious** [comment]
I'm reproducing this issue today on Debian, where a tabbed over .shrc that was copy-pasted has spaces instead of tabs:
```
alias                  m='$PAGER -M'
```
Using `db` with the cursor at the `m` causes `alias` to also be deleted, placing the cursor at the column 0.

**Comment by rjc** [comment]
Spaces vs tabs when copy-pasting using mouse in GUI, depends on the way clipboard is being handled by the software, i.e. your terminal emulator.

What's your `nvi2` config?

Also, have you made any changes to the source code before compiling it?

**Comment by concussious** [comment]
> .exrc

`set ru nu`

> changed source?

No, neither in the current case on Debian or previously on FreeBSD.

**Comment by rjc** [comment]
The base `{,n}vi` on _FreeBSD_, as well as the `nvi2` package on _OpenBSD_, behaves exactly the way @lichray described above.

I wasn't able to build `nvi2` on Debian, though, due to lack of `bdb` version _1.x_.

Could you post steps to reproduce your build on Debian, please?
