### ISSUE TITLE
no “search wrapped” notification on last character of file

### ISSUE THREAD

**Issue by bentley** [lichray/nvi2#28]
`$ printf "1\n\n" > foo.txt`
`$ nvi  -c2 foo.txt`

`/1`

Doesn’t print “Search wrapped” for the `/1` or `n` if done from the last line in this example.

`$ printf "1\na\n" > foo.txt`
`$ nvi  -c2 foo.txt`

`/1`

Same results for `/1` and all subsequent `n` done from the last line.

`$ printf "1\nab\n" > foo.txt`
`$ nvi -c2 foo.txt`

Same results for `\1` and all subsequent `n` done from the last character of the last line.

**Comment by lichray** [comment]
Can you help me test this patch?
```diff
diff --git a/common/search.c b/common/search.c
index a75ffde..5144e81 100644
--- a/common/search.c
+++ b/common/search.c
@@ -159,7 +159,7 @@ f_search(
 	recno_t lno;
 	regmatch_t match[1];
 	size_t coff, len;
-	int cnt, eval, rval, wrapped;
+	int cnt, eval, rval, wrapped = 0;
 	CHAR_T *l;
 
 	if (search_init(sp, FORWARD, ptrn, plen, eptrn, flags))
@@ -198,13 +198,14 @@ f_search(
 					return (1);
 				}
 				lno = 1;
+				wrapped = 1;
 			}
 		} else
 			coff = fm->cno + 1;
 	}
 
 	btype = BUSY_ON;
-	for (cnt = INTERRUPT_CHECK, rval = 1, wrapped = 0;; ++lno, coff = 0) {
+	for (cnt = INTERRUPT_CHECK, rval = 1;; ++lno, coff = 0) {
 		if (cnt-- == 0) {
 			if (INTERRUPTED(sp))
 				break;
```

The forward search has an "optimization", if the cursor sits on the last char of the last line, set the first line to search (`lno`) to 1, but `wrapped` is not updated there.  The backward search code has no such "optimization".

**Comment by bentley** [comment]
The patch works fine for me.
