### ISSUE TITLE
Doesn't compile on musl

### ISSUE THREAD

**Issue by nmeum** [lichray/nvi2#40]
nvi2 doesn't compile on [musl-libc](http://www.musl-libc.org/) under [alpine linux](http://alpinelinux.org/). There are several issue you run into when trying to compile it on a musl based system:

1. `sys/queue.h` isn't in POSIX and thus not in musl (maybe ship that file manually?).
2. `bitstring.h` isn't in musl (is it even available in glibc?) I know that it is available in `libbsd` but the include needs to be `<bsd/bitstring.h>` then.
3. Many files use type definitons from `<sys/types.h>` without including that header file.

I don't know if you are interested in musl support (I hope you are) but the nvi version written by Keith Bostic did run and compile fine on musl.

Here is the buildlog for version `2.1.3`:

```
$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DUSE_ICONV:Bool=False
-- The C compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for openpty
-- Looking for openpty - found
-- Looking for __b64_ntop
-- Looking for __b64_ntop - not found
-- Looking for include file libutil.h
-- Looking for include file libutil.h - not found
-- Looking for include file ncurses.h
-- Looking for include file ncurses.h - found
-- Looking for include file term.h
-- Looking for include file term.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/build
$ make
Scanning dependencies of target regex
[  1%] Building C object CMakeFiles/regex.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/regex/regcomp.c.o
[  2%] Building C object CMakeFiles/regex.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/regex/regerror.c.o
[  3%] Building C object CMakeFiles/regex.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/regex/regexec.c.o
[  4%] Building C object CMakeFiles/regex.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/regex/regfree.c.o
[  5%] Linking C static library libregex.a
[  5%] Built target regex
[  6%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/ex/version.h
[  6%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/cl/extern.h
[  7%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/common/extern.h
[  8%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/ex/extern.h
[  9%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/vi/extern.h
[ 10%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/common/options_def.h
[ 10%] Generating /home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/ex/ex_def.h
Scanning dependencies of target nvi
[ 11%] Building C object CMakeFiles/nvi.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/cl/cl_funcs.c.o
/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/cl/cl_funcs.c:17:23: fatal error: sys/queue.h: No such file or directory
compilation terminated.
CMakeFiles/nvi.dir/build.make:90: recipe for target 'CMakeFiles/nvi.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/cl/cl_funcs.c.o' failed
make[2]: *** [CMakeFiles/nvi.dir/home/soeren/code/aports/testing/nvi2/src/nvi2-2.1.3/cl/cl_funcs.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nvi.dir/all' failed
make[1]: *** [CMakeFiles/nvi.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Fixing issue 1. and 2. is of cause trivial, the question is if any other issue show up afterwards and if you are interested in general to provide support for musl.

**Comment by lichray** [comment]
On Mon, Nov 30, 2015 at 12:49 PM, nmeum <notifications@github.com> wrote:

> nvi2 doesn't compile on musl-libc <http://www.musl-libc.org/> under alpine
> linux <http://alpinelinux.org/>. There are several issue you run into
> when trying to compile it under a musl based system:
>
>    1. sys/queue.h isn't in POSIX and thus not in musl (maybe ship that
>    file manually?).
>    2. bitstring.h isn't in musl (is it even available in glibc?) I know
>    that it is available in libbsd but the include needs to be
>    <bsd/bitstring.h> then.
>
> You can try add `-isystem /usr/include/bsd -DLIBBSD_OVERLAY`


>
>    1. Many files use type definitons from <sys/types.h> without including
>    that header file.
>
> You can point out those to me and I probably will them.


>
>
> I don't know if you are interested in musl support (I hope you are) but
> the nvi version written by Keith Bostic did run and compile fine on musl.
>
I'm looking for demands not capabilities.  For example, if alpine linux
want to use nvi2 rather than vim-tiny as their vi implementation, I may
be able to help.  Otherwise, nvi2 is nothing better than vim, for instance,
as an editor in general.


> Fixing those issue 1. and 2. is of cause trivial, the question is if any
> other issue show up afterwards and if you are interested in general to
> provide support for musl.
>

If there is a demand like the aforementioned one, you can try workaound
those issues first, then give me some feedback so that I can get a feeling
about the amount of work.  If there is no demand, then no.

-- 
Zhihao Yuan, ID lichray
The best way to predict the future is to invent it.
___________________________________________________
4BSD -- http://bit.ly/blog4bsd
