### ISSUE TITLE
New Localisation?

### ISSUE THREAD

**Issue by bitigchi** [lichray/nvi2#67]
Hello,

I would like to volunteer to provide Turkish localisation for nvi2. Before I start working on it, I just wanted to check if it'd be acceptable/applicable.

Thanks!

**Comment by lichray** [comment]
Yes.  Please read catalog/README for contributing.  You can use the msgcat option to attach the new catalog at runtime for debugging.
________________________________

**Comment by bitigchi** [comment]
Thanks for the reply. I was able to create a new `english` file, but it seems a bit of a gibberish (layout-wise) compared to another file, say `german.base`. Is this expected? I can make out what the lines are but a bit afraid to mess up the messages order. Please see screenshot.

![Ekran Resmi 2020-02-24 22 50 34](https://user-images.githubusercontent.com/2769571/75186098-57343800-5758-11ea-92f7-48b746e23876.png)

**Comment by lichray** [comment]
The generated file after `make` are binary files, don't worry.  You only need to create new .base files.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by bitigchi** [comment]
Oh I didn't notice the `english.base` file. Got it now!

**Comment by bitigchi** [comment]
I opened #68 for this ticket. Also how can I build nvi2, say in macOS? I don't see any makefile.

**Comment by lichray** [comment]
The building instructions are in https://github.com/lichray/nvi2/wiki/Porting
In short, run `cmake` under the `build` directory (this is actually in-source build, just in a sub-directory), then `make`.

**Comment by lichray** [comment]
Forgot to add "closes:" when merging #68; thanks for the contribution.
