### ISSUE TITLE
expandtab is bypassed when lines are replaced with a ! shell command

### ISSUE THREAD

**Issue by leres** [lichray/nvi2#78]
If you are editing a file with expandtab on and pipe a line with 8 leading blanks through the fmt shell command (e.g. !!fmt<return), fmt replaces the blanks with a tab which end up in the input buffer.

I think this is a bug; if you agree I'll work on a fix.

**Comment by lichray** [comment]
I see.  It is also bypassed in Vim, but I think the proposed behavior is nice to have.
